from app import app, db
from models import Users, Pokemons, Cities, Regions, Favs, Type
from sqlalchemy import select

with app.app_context():
    db.drop_all()
    db.create_all()

    user1 = Users(email="pablo2@example.com", password="1234")
    user2 = Users(email="rocky@example.com", password="5678")
    db.session.add_all([user1, user2])
    db.session.commit()

    pokemon1 = Pokemons(name="Pikachu", type1=Type.Electric, desc="Cuando se enfada, este Pokémon descarga la energía que almacena en el interior de las bolsas de las mejillas.")
    pokemon2 = Pokemons(name="Charizard", type1=Type.Fire, type2=Type.Flying, desc="Cuando se enfurece de verdad, la llama de la punta de su cola se vuelve de color azul claro.")
    pokemon3 = Pokemons(name="Mewtwo", type1=Type.Psychic, desc="Su ADN es casi el mismo que el de Mew. Sin embargo, su tamaño y carácter son muy diferentes.")
    pokemon4 = Pokemons(name="Ursaring", type1=Type.Normal, desc="Su expresión dura y adusta se convierte en una sonrisa rebosante de felicidad en cuanto saborea la miel que tanto le gusta.")
    pokemon5 = Pokemons(name="Tentacruel", type1=Type.Water, type2=Type.Poison, desc="En muy raras ocasiones, cuando se produce una aparición masiva de Tentacruel, los Pokémon pez de los alrededores se esfuman sin dejar rastro.")
    pokemon6 = Pokemons(name="Venonat", type1=Type.Ghost, type2=Type.Poison, desc="Para quitarle la vida a su presa, se desliza en su sombra y espera su oportunidad en silencio.")
    pokemon7 = Pokemons(name="Raikou", type1=Type.Electric, desc="Raikou tiene la velocidad del rayo. Los rugidos de este Pokémon emiten ondas de choque que se esparcen vibrando por el aire y sacuden el suelo como si fueran auténticas descargas de rayo.")
    pokemon8 = Pokemons(name="Cloyster", type1=Type.Water,type2=Type.Ice, desc="A los Cloyster que viven en las fuertes corrientes marinas les crecen largas y afiladas púas en la concha.")
    db.session.add_all([pokemon1, pokemon2, pokemon3, pokemon4, pokemon5, pokemon6, pokemon7, pokemon8])
    db.session.commit()

    region1 = Regions(name="Kanto")
    region2 = Regions(name="Johto")
    region3 = Regions(name="Hoenn")
    region4 = Regions(name="Sinnoh")
    region5 = Regions(name="Teselia")
    region6 = Regions(name="Kalos")
    region7 = Regions(name="Alola")
    region8 = Regions(name="Galar")
    region9 = Regions(name="Paldea")
    db.session.add_all([region1, region2, region3, region4, region5, region6, region7, region8, region9])
    db.session.commit()

    city1 = Cities(name="Pueblo Paleta", region_id=region1.id, population=8)
    city2 = Cities(name="Pueblo Azalea", region_id=region2.id, population=28)
    city3 = Cities(name="Ciudad Luminalia", region_id=region6.id, population=416)
    city4 = Cities(name="Ciudad Porcelana", region_id=region5.id, population=301)
    city5 = Cities(name="Ciudad Hauoli", region_id=region7.id, population=151)
    city6 = Cities(name="Ciudad Jubileo", region_id=region4.id, population=129)
    city7 = Cities(name="Ciudad Calagua", region_id=region5.id, population=260)
    city8 = Cities(name="Ciudad Vetusta", region_id=region4.id, population=54)
    city9 = Cities(name="Ciudad Corazón", region_id=region4.id, population=91)
    city10 = Cities(name="Ciudad Malvalona", region_id=region3.id, population=78)
    city11 = Cities(name="Ciudad Trigal", region_id=region2.id, population=112)
    city12 = Cities(name="Ciudad Carmín", region_id=region1.id, population=29)
    db.session.add_all([city1, city2, city3, city4, city5, city6, city7, city8, city9, city10, city11, city12])
    db.session.commit()

    fav1 = Favs(user_id=user1.id,pokemon_id=pokemon3.id, city_id=0, region_id=0)
    fav2 = Favs(user_id=user1.id,pokemon_id=pokemon5.id, city_id=0, region_id=0)
    fav3 = Favs(user_id=user1.id,pokemon_id=pokemon8.id, city_id=0, region_id=0)
    fav4 = Favs(user_id=user2.id,pokemon_id=pokemon2.id, city_id=0, region_id=0)
    fav5 = Favs(user_id=user2.id,pokemon_id=pokemon5.id, city_id=0, region_id=0)
    fav6 = Favs(user_id=user1.id,pokemon_id=0, city_id=city4.id, region_id=0)
    fav7 = Favs(user_id=user1.id,pokemon_id=0, city_id=city3.id, region_id=0)
    fav8 = Favs(user_id=user2.id,pokemon_id=0, city_id=city1.id, region_id=0)
    fav9 = Favs(user_id=user2.id,pokemon_id=0, city_id=city7.id, region_id=0)
    fav10 = Favs(user_id=user1.id,pokemon_id=0, city_id=0, region_id=region1.id)
    fav11 = Favs(user_id=user2.id,pokemon_id=0, city_id=0, region_id=region2.id)
    fav12 = Favs(user_id=user2.id,pokemon_id=0, city_id=0, region_id=region9.id)
    db.session.add_all([fav1, fav2, fav3, fav4, fav5, fav6, fav7, fav8, fav9, fav10, fav11, fav12])
    db.session.commit()
    
    print("✅ Datos sembrados correctamente.")